services:
  book-manager-db:
    image: postgres:16-alpine
    container_name: book-manager-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: book_manager
    volumes:
      - postgres:/data/postgres
    networks:
      - main-net

  book-manager-app:
    image: danilchet/book-manager
    container_name: book-manager-app-container
    ports:
      - "8400:8400"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book-manager-db:5432/book_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - book-manager-db
    networks:
      - main-net

networks:
  main-net:
    driver: bridge

volumes:
  postgres: